import path from 'path';
import fs from 'fs';
import { Application, Request, Response, NextFunction } from 'express';
import XLSX from 'xlsx';
import { v4 as uuidv4 } from 'uuid';
import AdmZip from 'adm-zip';
import { RowDataPacket } from 'mysql2';
import Category from '../models/category';
import MenuItem from '../models/menuItem';
import TaxSettings from '../models/taxSettings';
import CurrencySettings from '../models/currencySettings';
import Cafe from '../models/cafe';
import User from '../models/user';
import CafeSettings from '../models/cafeSettings';
import PromoBanner from '../models/promoBanner';
import { pool } from '../config/database';
import { upload, zipUpload, imageUpload, multer } from '../config/multer';
import { auth, adminAuth, JWT_SECRET } from '../middleware/auth';
import { requireCafeMembership } from '../middleware/cafeAuth';
import { getOrderCafeId, requireOrderCafeScope } from './helpers';
import { requireFeature, requireActiveSubscription } from '../middleware/subscriptionAuth';
import { uploadLimiter } from '../middleware/rateLimiter';
import { publicImagesDir } from '../config/paths';
import logger from '../config/logger';

function getMenuCafeId(req: Request): number | null {
  let cafeId: number | null = null;
  if (req.user) {
    if (req.impersonation && req.impersonation.isImpersonating) {
      cafeId = req.impersonation.cafeId ?? null;
    } else if (req.user.cafe_id) {
      cafeId = req.user.cafe_id;
    }
  }
  if (req.user && req.user.role === 'superadmin' && req.query.cafeId != null && req.query.cafeId !== '') {
    const parsed = parseInt(String(req.query.cafeId), 10);
    if (Number.isInteger(parsed) && parsed > 0) {
      cafeId = parsed;
    }
  }
  return cafeId;
}

export default function registerMenu(app: Application): void {
  app.get('/api/categories', auth, async (req: Request, res: Response) => {
    try {
      const cafeId = getMenuCafeId(req);
      const categories = await Category.getAll(cafeId);
      res.json(categories);
    } catch (error) {
      logger.error('Error fetching categories:', error as Error);
      res.status(500).json({ error: 'Failed to fetch categories' });
    }
  });

  app.get('/api/categories/with-counts', auth, async (req: Request, res: Response) => {
    try {
      const cafeId = getMenuCafeId(req);
      const categories = await Category.getWithItemCounts(cafeId);
      res.json(categories);
    } catch (error) {
      logger.error('Error fetching categories with counts:', error as Error);
      res.status(500).json({ error: 'Failed to fetch categories with counts' });
    }
  });

  app.post('/api/categories/generate', auth, async (req: Request, res: Response) => {
    try {
      const cafeId = getMenuCafeId(req);
      if (!cafeId) {
        return res.status(400).json({
          error: 'Unable to determine cafe. Please ensure you are logged in and belong to a cafe.'
        });
      }
      const categories = await Category.generateFromMenuItems(cafeId);
      res.json({
        message: 'Categories generated successfully from menu items',
        categories
      });
    } catch (error) {
      logger.error('Error generating categories from menu items:', error as Error);
      res.status(500).json({ error: (error as Error).message || 'Failed to generate categories' });
    }
  });

  app.get('/api/categories/auto-generated', auth, async (req: Request, res: Response) => {
    try {
      const cafeId = getMenuCafeId(req);
      const categories = await Category.getAutoGenerated(cafeId);
      res.json(categories);
    } catch (error) {
      logger.error('Error fetching auto-generated categories:', error as Error);
      res.status(500).json({ error: 'Failed to fetch auto-generated categories' });
    }
  });

  app.post('/api/categories', auth, async (req: Request, res: Response) => {
    try {
      const body = req.body as { name?: string; description?: string; sort_order?: number };
      const { name, description, sort_order } = body;
      if (!name) {
        return res.status(400).json({ error: 'Category name is required' });
      }
      const cafeId = getMenuCafeId(req);
      if (!cafeId) {
        return res.status(400).json({
          error: 'Unable to determine cafe. Please ensure you are logged in and belong to a cafe.'
        });
      }
      const newCategory = {
        name: name.trim(),
        description: description ? description.trim() : '',
        sort_order: sort_order || 0,
        cafe_id: cafeId
      };
      const createdCategory = await Category.create(newCategory);
      res.status(201).json(createdCategory);
    } catch (error) {
      logger.error('Error creating category:', error as Error);
      res.status(500).json({ error: (error as Error).message || 'Failed to create category' });
    }
  });

  app.put('/api/categories/:id', auth, async (req: Request, res: Response) => {
    try {
      const id = req.params.id as string;
      const body = req.body as { name?: string; description?: string; sort_order?: number; is_active?: boolean };
      const { name, description, sort_order, is_active } = body;
      if (!name) {
        return res.status(400).json({ error: 'Category name is required' });
      }
      const cafeId = getMenuCafeId(req);
      const updatedCategory = await Category.update(
        parseInt(id, 10),
        {
          name: name.trim(),
          description: description ? description.trim() : '',
          sort_order: sort_order || 0,
          is_active: is_active !== undefined ? is_active : true
        },
        cafeId ?? undefined
      );
      res.json(updatedCategory);
    } catch (error) {
      logger.error('Error updating category:', error as Error);
      res.status(500).json({ error: (error as Error).message || 'Failed to update category' });
    }
  });

  app.delete('/api/categories/:id', auth, async (req: Request, res: Response) => {
    try {
      const id = req.params.id as string;
      const cafeId = getMenuCafeId(req);
      const deleted = await Category.delete(parseInt(id, 10), cafeId ?? undefined);
      if (!deleted) {
        return res.status(404).json({ error: 'Category not found' });
      }
      res.status(204).send();
    } catch (error) {
      logger.error('Error deleting category:', error as Error);
      res.status(500).json({ error: (error as Error).message || 'Failed to delete category' });
    }
  });

  // Public menu (no auth required)
  app.get('/api/menu', async (req: Request, res: Response) => {
    try {
      let cafeId: number | null = null;
      const token = req.header('Authorization')?.replace('Bearer ', '');
      if (token) {
        try {
          const jwt = await import('jsonwebtoken');
          const decoded = jwt.verify(token, JWT_SECRET, { clockTolerance: 600 }) as {
            userId: number;
            impersonatedCafeId?: number;
          };
          const user = await User.findById(decoded.userId);
          if (user) {
            if (decoded.impersonatedCafeId) {
              cafeId = decoded.impersonatedCafeId;
            } else {
              const userWithCafe = await User.findByIdWithCafe(user.id);
              if (userWithCafe?.cafe_id) cafeId = userWithCafe.cafe_id;
            }
          }
        } catch {
          // token invalid
        }
      }
      if (!cafeId) {
        const cafeSlug = (req.query.cafeSlug as string) || 'default';
        try {
          const cafe = await Cafe.getBySlug(cafeSlug);
          if (cafe) cafeId = cafe.id;
        } catch {
          // ignore
        }
        if (!cafeId) {
          const firstCafe = await Cafe.getFirstActive();
          if (firstCafe) cafeId = firstCafe.id;
        }
      }
      logger.debug('[GET /api/menu] Fetching menu items', {
        cafeId,
        hasToken: !!token,
        cafeSlug: req.query.cafeSlug
      });
      if (!cafeId) {
        return res.status(400).json({
          error: 'Cafe context required. Provide ?cafeSlug= or log in with a cafe account.',
          code: 'CAFE_REQUIRED'
        });
      }
      const menuItems = await MenuItem.getAll(cafeId);
      res.json(menuItems);
    } catch (error) {
      logger.error('[GET /api/menu] Error fetching menu items:', error as Error);
      res.status(500).json({ error: 'Failed to fetch menu items' });
    }
  });

  app.get(
    '/api/admin/menu',
    auth,
    requireActiveSubscription,
    requireFeature('menu_management'),
    async (req: Request, res: Response) => {
      try {
        let cafeId: number | null = null;
        if (req.user) {
          if (req.impersonation?.isImpersonating) {
            cafeId = req.impersonation.cafeId ?? null;
          } else {
            const userWithCafe = await User.findByIdWithCafe(req.user.id);
            if (userWithCafe?.cafe_id) cafeId = userWithCafe.cafe_id;
          }
        }
        if (req.user?.role === 'superadmin' && req.query.cafeId) {
          cafeId = parseInt(String(req.query.cafeId), 10);
        }
        if (!cafeId) {
          try {
            const defaultCafe = await Cafe.getBySlug('default');
            if (defaultCafe) cafeId = defaultCafe.id;
          } catch {
            //
          }
        }
        const menuItems = await MenuItem.getAll(cafeId!);
        res.json(menuItems);
      } catch (error) {
        logger.error('[GET /api/admin/menu] Error fetching menu items:', error as Error);
        res.status(500).json({ error: 'Failed to fetch menu items' });
      }
    }
  );

  app.get(
    '/api/menu/grouped',
    auth,
    requireActiveSubscription,
    requireFeature('menu_management'),
    async (req: Request, res: Response) => {
      try {
        let cafeId: number | null = null;
        if (req.user) {
          const userWithCafe = await User.findByIdWithCafe(req.user.id);
          if (userWithCafe?.cafe_id) cafeId = userWithCafe.cafe_id;
        }
        if (!cafeId) {
          try {
            const defaultCafe = await Cafe.getBySlug('default');
            if (defaultCafe) cafeId = defaultCafe.id;
          } catch {
            //
          }
        }
        const menuItems = await MenuItem.getGroupedByCategory(cafeId!);
        res.json(menuItems);
      } catch (error) {
        logger.error('Error fetching menu items grouped:', error as Error);
        res.status(500).json({ error: 'Failed to fetch menu items grouped' });
      }
    }
  );

  app.post(
    '/api/menu',
    auth,
    requireActiveSubscription,
    requireFeature('menu_management'),
    async (req: Request, res: Response) => {
      try {
        const body = req.body as {
          category_id?: number;
          name?: string;
          description?: string;
          price?: number | string;
          sort_order?: number;
          image_url?: string | null;
        };
        const { category_id, name, description, price, sort_order, image_url } = body;
        if (!category_id || !name || !price) {
          return res.status(400).json({ error: 'Category, name and price are required' });
        }
        let cafeId: number | null = null;
        if (req.user) {
          const userWithCafe = await User.findByIdWithCafe(req.user.id);
          if (userWithCafe?.cafe_id) cafeId = userWithCafe.cafe_id;
        }
        if (!cafeId) {
          try {
            const defaultCafe = await Cafe.getBySlug('default');
            if (defaultCafe) cafeId = defaultCafe.id;
          } catch {
            //
          }
        }
        const newItem = {
          category_id,
          name: name.trim(),
          description: description ? description.trim() : '',
          price: parseFloat(String(price)),
          sort_order: sort_order || 0,
          image_url: image_url || null,
          cafe_id: cafeId!
        };
        const createdItem = await MenuItem.create(newItem);
        res.status(201).json(createdItem);
      } catch (error) {
        logger.error('Error creating menu item:', error as Error);
        res.status(500).json({ error: 'Failed to create menu item' });
      }
    }
  );

  app.put(
    '/api/menu/:id',
    auth,
    requireCafeMembership,
    requireActiveSubscription,
    requireFeature('menu_management'),
    async (req: Request, res: Response) => {
      try {
        const id = req.params.id as string;
        const body = req.body as {
          category_id?: number;
          name?: string;
          description?: string;
          price?: number | string;
          sort_order?: number;
          is_active?: boolean;
          image_url?: string | null;
        };
        const { category_id, name, description, price, sort_order, is_active, image_url } = body;
        if (!category_id || !name || !price) {
          return res.status(400).json({ error: 'Category, name and price are required' });
        }
        const cafeId = getOrderCafeId(req);
        const updatedItem = await MenuItem.update(
          parseInt(id, 10),
          {
            category_id,
            name: name.trim(),
            description: description ? description.trim() : '',
            price: parseFloat(String(price)),
            sort_order: sort_order || 0,
            is_available: is_active !== undefined ? is_active : true,
            image_url: image_url || null
          },
          cafeId ?? null
        );
        res.json(updatedItem);
      } catch (error) {
        logger.error('Error updating menu item:', error as Error);
        res.status(500).json({ error: 'Failed to update menu item' });
      }
    }
  );

  app.delete(
    '/api/menu/:id',
    auth,
    requireCafeMembership,
    requireActiveSubscription,
    requireFeature('menu_management'),
    async (req: Request, res: Response) => {
      try {
        const id = req.params.id as string;
        const cafeId = getOrderCafeId(req);
        const deleted = await MenuItem.delete(parseInt(id, 10), cafeId ?? null);
        if (!deleted) {
          return res.status(404).json({ error: 'Menu item not found' });
        }
        res.status(204).send();
      } catch (error) {
        logger.error('Error deleting menu item:', error as Error);
        res.status(500).json({ error: 'Failed to delete menu item' });
      }
    }
  );

  app.get('/api/menu/export', auth, async (req: Request, res: Response) => {
    try {
      let cafeId = getMenuCafeId(req);
      if (!cafeId) {
        try {
          const defaultCafe = await Cafe.getBySlug('default');
          if (defaultCafe) cafeId = defaultCafe.id;
        } catch {
          //
        }
      }
      if (!cafeId) {
        return res.status(400).json({
          error: 'Unable to determine cafe. Please ensure you are logged in and belong to a cafe.'
        });
      }
      const menuItems = await MenuItem.getAll(cafeId);
      if (!menuItems || menuItems.length === 0) {
        return res.status(404).json({
          error: 'No menu items found for this cafe. Please add menu items before exporting.'
        });
      }
      const allCategories = await Category.getAll(cafeId);
      const usedCategoryIds = new Set(menuItems.map((item) => item.category_id).filter(Boolean));
      const categories = allCategories.filter((cat) => usedCategoryIds.has(cat.id));
      const workbook = XLSX.utils.book_new();
      const menuData = menuItems.map((item) => {
        let imageFilename = '';
        if (item.image_url) {
          imageFilename = path.basename(item.image_url);
        }
        return {
          Category: item.category_name || 'Uncategorized',
          'Item Name': item.name,
          Description: item.description || '',
          Price: item.price,
          Image: imageFilename,
          'Sort Order': item.sort_order || 0
        };
      });
      const menuWorksheet = XLSX.utils.json_to_sheet(menuData);
      XLSX.utils.book_append_sheet(workbook, menuWorksheet, 'Menu Items');
      const categoryData = categories.map((cat) => ({
        'Category Name': cat.name,
        Description: cat.description || '',
        'Sort Order': cat.sort_order || 0
      }));
      const categoryWorksheet = XLSX.utils.json_to_sheet(categoryData);
      XLSX.utils.book_append_sheet(workbook, categoryWorksheet, 'Categories');
      const buffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' });
      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', 'attachment; filename=palm-cafe-menu.xlsx');
      res.send(buffer);
    } catch (error) {
      logger.error('Error exporting menu:', error as Error);
      res.status(500).json({ error: 'Failed to export menu: ' + (error as Error).message });
    }
  });

  app.post('/api/menu/import', auth, upload.single('file'), async (req: Request, res: Response) => {
    try {
      if (!req.file) {
        return res.status(400).json({ error: 'No file uploaded' });
      }
      let cafeId = getMenuCafeId(req);
      if (!cafeId) {
        try {
          const defaultCafe = await Cafe.getBySlug('default');
          if (defaultCafe) cafeId = defaultCafe.id;
        } catch {
          //
        }
      }
      if (!cafeId) {
        return res.status(400).json({
          error: 'Unable to determine cafe. Please ensure you are logged in and belong to a cafe.'
        });
      }
      const workbook = XLSX.read(req.file.buffer as Buffer, { type: 'buffer' });
      const menuSheet = workbook.Sheets['Menu Items'];
      if (!menuSheet) {
        return res.status(400).json({ error: 'Menu Items sheet not found in Excel file' });
      }
      const menuData = XLSX.utils.sheet_to_json(menuSheet) as Record<string, unknown>[];
      if (menuData.length === 0) {
        return res.status(400).json({ error: 'No data found in Menu Items sheet' });
      }
      const categories = await Category.getAll(cafeId);
      const categoryMap: Record<string, number> = {};
      categories.forEach((cat) => {
        categoryMap[cat.name.toLowerCase()] = cat.id;
      });
      const itemsToImport: { category_id: number; name: string; description: string; price: number; sort_order: number; image_url: string | null; cafe_id: number }[] = [];
      const errors: string[] = [];
      for (let i = 0; i < menuData.length; i++) {
        const row = menuData[i];
        const rowNumber = i + 2;
        try {
          const itemName = (row['Item Name'] ?? row['item name'] ?? row['Item name']) as string | undefined;
          const priceVal = (row['Price'] ?? row['price'] ?? row['PRICE']) as string | number | undefined;
          if (!itemName || priceVal == null) {
            errors.push(`Row ${rowNumber}: Item Name and Price are required`);
            continue;
          }
          const categoryName = String(row['Category'] ?? row['category'] ?? row['CATEGORY'] ?? '').trim();
          let categoryId: number | null = categoryMap[categoryName.toLowerCase()] ?? null;
          if (categoryName && !categoryId) {
            try {
              const created = await Category.create({
                name: categoryName,
                description: '',
                sort_order: categories.length + 1,
                cafe_id: cafeId
              });
              categoryId = created.id;
              categoryMap[categoryName.toLowerCase()] = categoryId;
              categories.push(created as unknown as import('../models/category').CategoryRow & { id: number });
            } catch (catError) {
              if ((catError as Error).message.includes('Duplicate entry') || (catError as Error).message.includes('UNIQUE constraint')) {
                const [existing] = await pool.execute(
                  'SELECT id, name, is_active FROM categories WHERE name = ? AND cafe_id = ? LIMIT 1',
                  [categoryName, cafeId]
                ) as [RowDataPacket[], unknown];
                const ex = existing as (RowDataPacket & { id: number; is_active?: number })[];
                if (ex.length > 0) {
                  categoryId = ex[0].id;
                  categoryMap[categoryName.toLowerCase()] = categoryId;
                  if (!ex[0].is_active) {
                    await pool.execute('UPDATE categories SET is_active = TRUE WHERE id = ?', [categoryId]);
                  }
                } else {
                  errors.push(`Row ${rowNumber}: Category "${categoryName}" already exists but couldn't be found for this cafe`);
                  continue;
                }
              } else {
                errors.push(`Row ${rowNumber}: Failed to create category "${categoryName}": ${(catError as Error).message}`);
                continue;
              }
            }
          } else if (!categoryName) {
            errors.push(`Row ${rowNumber}: Category is required. Please provide a category name.`);
            continue;
          }
          const priceNum = parseFloat(String(priceVal));
          if (isNaN(priceNum) || priceNum <= 0) {
            errors.push(`Row ${rowNumber}: Invalid price. Price must be a positive number.`);
            continue;
          }
          let imageUrl: string | null = null;
          const imageValue = (row['Image'] ?? row['image'] ?? row['IMAGE'] ?? '') as string;
          if (imageValue) {
            const s = imageValue.toString().trim();
            if (s.startsWith('http://') || s.startsWith('https://')) imageUrl = s;
            else if (s.startsWith('/')) imageUrl = s;
            else if (s) imageUrl = `/images/${s}`;
          }
          itemsToImport.push({
            category_id: categoryId!,
            name: itemName.toString().trim(),
            description: String(row['Description'] ?? row['description'] ?? row['DESCRIPTION'] ?? '').trim(),
            price: priceNum,
            sort_order: Number(row['Sort Order'] ?? row['sort_order'] ?? 0) || 0,
            image_url: imageUrl,
            cafe_id: cafeId
          });
        } catch (err) {
          errors.push(`Row ${rowNumber}: ${(err as Error).message}`);
        }
      }
      const importResults = await MenuItem.bulkImport(itemsToImport);
      const successCount = importResults.filter((r) => r.success).length;
      const failureCount = importResults.filter((r) => !r.success).length;
      const allErrors = errors.concat(importResults.filter((r) => !r.success).map((r) => r.error).filter((e): e is string => e != null));
      res.json({
        message: `Import completed. ${successCount} items imported successfully, ${failureCount} failed.`,
        successCount,
        failureCount,
        errors: allErrors.length > 0 ? allErrors : undefined,
        cafeId
      });
    } catch (error) {
      logger.error('[MENU IMPORT] Error importing menu:', error as Error);
      res.status(500).json({
        error: 'Failed to import menu',
        details: (error as Error).message,
        stack: process.env.NODE_ENV === 'development' ? (error as Error).stack : undefined
      });
    }
  });

  app.post(
    '/api/menu/import-zip',
    auth,
    requireActiveSubscription,
    requireFeature('menu_management'),
    (req: Request, res: Response, next: NextFunction) => {
      zipUpload.single('file')(req, res, (err: unknown) => {
        if (err) {
          if (err instanceof multer.MulterError) {
            if (err.code === 'LIMIT_FILE_SIZE') {
              return res.status(400).json({ error: 'File too large. Maximum size is 50MB.' });
            }
            return res.status(400).json({ error: `Upload error: ${err.message}` });
          }
          return res.status(400).json({ error: (err as Error).message || 'Invalid file type' });
        }
        next();
      });
    },
    async (req: Request, res: Response) => {
      const tempDir = path.join(__dirname, '..', 'temp', `import-${Date.now()}-${uuidv4()}`);
      try {
        if (!req.file) {
          return res.status(400).json({ error: 'No ZIP file uploaded. Please select a ZIP file.' });
        }
        const isValidZip =
          req.file.originalname.toLowerCase().endsWith('.zip') ||
          req.file.mimetype === 'application/zip' ||
          req.file.mimetype === 'application/x-zip-compressed' ||
          req.file.mimetype === 'application/x-zip' ||
          (req.file.mimetype && req.file.mimetype.includes('zip'));
        if (!isValidZip) {
          return res.status(400).json({
            error: `Invalid file type. Expected ZIP file, got: ${req.file.mimetype || 'unknown'}. File name: ${req.file.originalname}`
          });
        }
        let cafeId = getMenuCafeId(req);
        if (!cafeId) {
          try {
            const defaultCafe = await Cafe.getBySlug('default');
            if (defaultCafe) cafeId = defaultCafe.id;
          } catch {
            //
          }
        }
        if (!cafeId) {
          return res.status(400).json({
            error: 'Unable to determine cafe. Please ensure you are logged in and belong to a cafe.'
          });
        }
        if (!fs.existsSync(tempDir)) {
          fs.mkdirSync(tempDir, { recursive: true });
        }
        let zip: AdmZip;
        try {
          zip = new AdmZip(req.file.buffer as Buffer);
          zip.extractAllTo(tempDir, true);
        } catch (zipError) {
          return res.status(400).json({
            error: `Failed to extract ZIP file: ${(zipError as Error).message}. Please ensure the file is a valid ZIP archive.`
          });
        }
        const files = fs.readdirSync(tempDir);
        let excelPath: string | null = null;
        for (const file of files) {
          if (file.toLowerCase() === 'menu.xlsx' || file.toLowerCase().endsWith('.xlsx')) {
            excelPath = path.join(tempDir, file);
            break;
          }
        }
        if (!excelPath) {
          const findExcel = (dir: string): string | null => {
            const items = fs.readdirSync(dir);
            for (const item of items) {
              const itemPath = path.join(dir, item);
              if (fs.statSync(itemPath).isDirectory()) {
                const found = findExcel(itemPath);
                if (found) return found;
              } else if (item.toLowerCase().endsWith('.xlsx')) {
                return path.join(dir, item);
              }
            }
            return null;
          };
          excelPath = findExcel(tempDir);
        }
        if (!excelPath) {
          return res.status(400).json({ error: 'Excel file (menu.xlsx) not found in ZIP archive' });
        }
        const findImagesDir = (dir: string): string | null => {
          const items = fs.readdirSync(dir);
          for (const item of items) {
            const itemPath = path.join(dir, item);
            if (fs.statSync(itemPath).isDirectory() && item.toLowerCase() === 'images') {
              return itemPath;
            }
          }
          for (const item of items) {
            const itemPath = path.join(dir, item);
            if (fs.statSync(itemPath).isDirectory()) {
              const found = findImagesDir(itemPath);
              if (found) return found;
            }
          }
          return null;
        };
        const imagesDir = findImagesDir(tempDir) || tempDir;
        const imageMap = new Map<string, string>();
        const addImages = (dir: string) => {
          try {
            const imageFiles = fs.readdirSync(dir);
            const exts = ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp'];
            for (const imageFile of imageFiles) {
              const imagePath = path.join(dir, imageFile);
              if (fs.statSync(imagePath).isFile()) {
                const ext = path.extname(imageFile).toLowerCase();
                if (exts.includes(ext)) {
                  imageMap.set(imageFile.toLowerCase(), imagePath);
                  imageMap.set(imageFile, imagePath);
                }
              }
            }
          } catch {
            //
          }
        };
        addImages(imagesDir);
        let workbook: XLSX.WorkBook;
        try {
          workbook = XLSX.readFile(excelPath);
        } catch {
          return res.status(400).json({
            error: 'Failed to read Excel file. Please ensure the file is a valid Excel (.xlsx) file.'
          });
        }
        const menuSheet = workbook.Sheets['Menu Items'] || workbook.Sheets[workbook.SheetNames[0]];
        if (!menuSheet) {
          return res.status(400).json({ error: 'Menu Items sheet not found in Excel file.' });
        }
        const menuData = XLSX.utils.sheet_to_json(menuSheet) as Record<string, unknown>[];
        if (menuData.length === 0) {
          return res.status(400).json({ error: 'No data found in Menu Items sheet' });
        }
        const categories = await Category.getAll(cafeId);
        const categoryMap: Record<string, number> = {};
        categories.forEach((cat) => {
          categoryMap[cat.name.toLowerCase()] = cat.id;
        });
        if (!fs.existsSync(publicImagesDir)) {
          fs.mkdirSync(publicImagesDir, { recursive: true });
        }
        const itemsToImport: { category_id: number; name: string; description: string; price: number; sort_order: number; image_url: string | null; cafe_id: number }[] = [];
        const errors: string[] = [];
        const imageStats = { attached: 0, missing: 0, invalid: 0 };
        for (let i = 0; i < menuData.length; i++) {
          const row = menuData[i];
          const rowNumber = i + 2;
          try {
            const itemName = (row['Item Name'] ?? row['item name'] ?? row['Name']) as string | undefined;
            const priceVal = (row['Price'] ?? row['price'] ?? row['PRICE']) as string | number | undefined;
            if (!itemName || !priceVal) {
              errors.push(`Row ${rowNumber}: Item Name and Price are required.`);
              continue;
            }
            const categoryName = String(row['Category'] ?? row['category'] ?? row['CATEGORY'] ?? '').trim();
            let categoryId: number | null = categoryMap[categoryName.toLowerCase()] ?? null;
            if (categoryName && !categoryId) {
              try {
                const created = await Category.create({
                  name: categoryName,
                  description: '',
                  sort_order: categories.length + 1,
                  cafe_id: cafeId
                });
                categoryId = created.id;
                categoryMap[categoryName.toLowerCase()] = categoryId;
                categories.push(created as unknown as import('../models/category').CategoryRow & { id: number });
              } catch (catError) {
                if ((catError as Error).message.includes('Duplicate entry') || (catError as Error).message.includes('UNIQUE constraint')) {
                  const [existing] = await pool.execute(
                    'SELECT id, name, is_active FROM categories WHERE name = ? AND cafe_id = ? LIMIT 1',
                    [categoryName, cafeId]
                  ) as [RowDataPacket[], unknown];
                  const ex = existing as (RowDataPacket & { id: number; is_active?: number })[];
                  if (ex.length > 0) {
                    categoryId = ex[0].id;
                    categoryMap[categoryName.toLowerCase()] = categoryId;
                    if (!ex[0].is_active) {
                      await pool.execute('UPDATE categories SET is_active = TRUE WHERE id = ?', [categoryId]);
                    }
                  } else {
                    errors.push(`Row ${rowNumber}: Category "${categoryName}" already exists but couldn't be found for this cafe`);
                    continue;
                  }
                } else {
                  errors.push(`Row ${rowNumber}: Failed to create category "${categoryName}": ${(catError as Error).message}`);
                  continue;
                }
              }
            } else if (!categoryName) {
              errors.push(`Row ${rowNumber}: Category is required.`);
              continue;
            }
            const priceNum = parseFloat(String(priceVal));
            if (isNaN(priceNum) || priceNum <= 0) {
              errors.push(`Row ${rowNumber}: Invalid price. Price must be a positive number.`);
              continue;
            }
            let imageUrl: string | null = null;
            let imageFilename = (row['Image'] ?? row['image'] ?? row['IMAGE']) as string | undefined;
            if (imageFilename && imageFilename.toString().trim()) {
              const imageFilenameStr = imageFilename.toString().trim();
              let imagePath = imageMap.get(imageFilenameStr) ?? imageMap.get(imageFilenameStr.toLowerCase());
              if (!imagePath && imageFilenameStr.includes('/')) {
                imagePath = imageMap.get(path.basename(imageFilenameStr)) ?? undefined;
              }
              if (imagePath && fs.existsSync(imagePath)) {
                const ext = path.extname(imageFilenameStr).toLowerCase();
                if (['.jpg', '.jpeg', '.png', '.gif', '.webp'].includes(ext)) {
                  const uniqueFileName = `menu-item-${Date.now()}-${i}-${uuidv4()}${ext}`;
                  const targetPath = path.join(publicImagesDir, uniqueFileName);
                  try {
                    fs.copyFileSync(imagePath, targetPath);
                    imageUrl = `/images/${uniqueFileName}`;
                    imageStats.attached++;
                  } catch {
                    errors.push(`Row ${rowNumber}: Failed to copy image "${imageFilenameStr}".`);
                    imageStats.invalid++;
                  }
                }
              } else {
                errors.push(`Row ${rowNumber}: Image file "${imageFilenameStr}" not found in ZIP archive.`);
                imageStats.missing++;
              }
            }
            itemsToImport.push({
              category_id: categoryId!,
              name: itemName.toString().trim(),
              description: String(row['Description'] ?? row['description'] ?? row['DESCRIPTION'] ?? '').trim(),
              price: priceNum,
              sort_order: Number(row['Sort Order'] ?? row['sort_order'] ?? 0) || 0,
              image_url: imageUrl,
              cafe_id: cafeId
            });
          } catch (err) {
            errors.push(`Row ${rowNumber}: ${(err as Error).message}`);
          }
        }
        const importResults = await MenuItem.bulkImport(itemsToImport);
        const successCount = importResults.filter((r) => r.success).length;
        const failureCount = importResults.filter((r) => !r.success).length;
        importResults.filter((r) => !r.success).forEach((err) => {
          errors.push(`Failed to create item "${(err as { item?: { name?: string } }).item?.name || 'unknown'}": ${err.error}`);
        });
        res.json({
          message: `Import completed. ${successCount} items imported successfully, ${failureCount} failed.`,
          successCount,
          failureCount,
          imageStats: { attached: imageStats.attached, missing: imageStats.missing, invalid: imageStats.invalid },
          errors: errors.length > 0 ? errors : undefined,
          cafeId
        });
      } catch (error) {
        logger.error('[ZIP IMPORT] Error:', error as Error);
        res.status(500).json({
          error: 'Failed to import menu: ' + (error as Error).message,
          details: (error as Error).message,
          stack: process.env.NODE_ENV === 'development' ? (error as Error).stack : undefined
        });
      } finally {
        try {
          if (fs.existsSync(tempDir)) {
            fs.rmSync(tempDir, { recursive: true, force: true });
          }
        } catch {
          logger.error('Error cleaning up temp directory');
        }
      }
    }
  );

  app.get('/api/tax-settings', auth, requireOrderCafeScope, async (req: Request, res: Response) => {
    try {
      const cafeId = getOrderCafeId(req);
      const taxSettings = await TaxSettings.getCurrent(cafeId);
      res.json(taxSettings);
    } catch (error) {
      logger.error('Error fetching tax settings:', error as Error);
      res.status(500).json({ error: 'Failed to fetch tax settings' });
    }
  });

  app.get('/api/tax-settings/menu', async (req: Request, res: Response) => {
    try {
      const cafeSlug = (req.query.cafeSlug as string) || 'default';
      const cafe = await Cafe.getBySlug(cafeSlug);
      const cafeId = cafe ? cafe.id : null;
      const taxSettings = await TaxSettings.getCurrent(cafeId);
      res.json({
        show_tax_in_menu: taxSettings.show_tax_in_menu,
        tax_rate: taxSettings.tax_rate
      });
    } catch (error) {
      logger.error('Error fetching tax settings for menu:', error as Error);
      res.status(500).json({ error: 'Failed to fetch tax settings for menu' });
    }
  });

  app.get('/api/menu/featured', async (req: Request, res: Response) => {
    try {
      const cafeSlug = (req.query.cafeSlug as string) || 'default';
      const cafe = await Cafe.getBySlug(cafeSlug);
      if (!cafe) {
        return res.status(404).json({ error: 'Cafe not found' });
      }
      const rawLimit = parseInt(String(req.query.limit), 10);
      const limit = Number.isNaN(rawLimit) ? 6 : Math.min(50, Math.max(1, rawLimit));
      const items = await MenuItem.getFeatured(cafe.id, limit);
      res.json({ items });
    } catch (error) {
      logger.error('Error fetching featured items:', error as Error);
      res.status(500).json({ error: 'Failed to fetch featured items' });
    }
  });

  app.get('/api/menu/public-info', async (req: Request, res: Response) => {
    try {
      const cafeSlug = (req.query.cafeSlug as string) || 'default';
      const cafe = await Cafe.getBySlug(cafeSlug);
      if (!cafe) {
        return res.status(404).json({ error: 'Cafe not found' });
      }
      res.json({
        name: cafe.name || '',
        address: cafe.address || '',
        phone: cafe.phone || '',
        email: cafe.email || '',
        website: cafe.website || '',
        opening_hours: null
      });
    } catch (error) {
      logger.error('Error fetching cafe public info:', error as Error);
      res.status(500).json({ error: 'Failed to fetch cafe public info' });
    }
  });

  app.get('/api/menu/branding', async (req: Request, res: Response) => {
    try {
      const cafeSlug = (req.query.cafeSlug as string) || 'default';
      const cafe = await Cafe.getBySlug(cafeSlug);
      if (!cafe) {
        return res.status(404).json({ error: 'Cafe not found' });
      }
      let heroImageUrl: string | null = null;
      let promoBannerImageUrl: string | null = null;
      let logoUrl: string | null = null;
      try {
        const [columns] = await pool.execute(`
          SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
          WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cafe_settings' AND COLUMN_NAME = 'cafe_id'
        `) as [RowDataPacket[], unknown];
        if ((columns as RowDataPacket[]).length > 0) {
          const [brandingColumns] = await pool.execute(`
            SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cafe_settings'
            AND COLUMN_NAME IN ('hero_image_url', 'promo_banner_image_url', 'logo_url')
          `) as [RowDataPacket[], unknown];
          const existingBrandingColumns = (brandingColumns as (RowDataPacket & { COLUMN_NAME: string })[]).map((c) => c.COLUMN_NAME);
          if (existingBrandingColumns.length > 0) {
            const selectColumns = existingBrandingColumns.join(', ');
            const [settings] = await pool.execute(
              `SELECT ${selectColumns} FROM cafe_settings WHERE cafe_id = ? AND is_active = TRUE ORDER BY created_at DESC LIMIT 1`,
              [cafe.id]
            ) as [RowDataPacket[], unknown];
            const s = settings as (RowDataPacket & { hero_image_url?: string; promo_banner_image_url?: string; logo_url?: string })[];
            if (s.length > 0) {
              if (existingBrandingColumns.includes('hero_image_url')) heroImageUrl = s[0].hero_image_url ?? null;
              if (existingBrandingColumns.includes('promo_banner_image_url')) promoBannerImageUrl = s[0].promo_banner_image_url ?? null;
              if (existingBrandingColumns.includes('logo_url')) logoUrl = s[0].logo_url ?? null;
            }
          }
        } else {
          const [brandingColumns] = await pool.execute(`
            SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cafe_settings'
            AND COLUMN_NAME IN ('hero_image_url', 'promo_banner_image_url', 'logo_url')
          `) as [RowDataPacket[], unknown];
          const existingBrandingColumns = (brandingColumns as (RowDataPacket & { COLUMN_NAME: string })[]).map((c) => c.COLUMN_NAME);
          if (existingBrandingColumns.length > 0) {
            const selectColumns = existingBrandingColumns.join(', ');
            const [settings] = await pool.execute(
              `SELECT ${selectColumns} FROM cafe_settings WHERE is_active = TRUE ORDER BY created_at DESC LIMIT 1`
            ) as [RowDataPacket[], unknown];
            const s = settings as (RowDataPacket & { hero_image_url?: string; promo_banner_image_url?: string; logo_url?: string })[];
            if (s.length > 0) {
              if (existingBrandingColumns.includes('hero_image_url')) heroImageUrl = s[0].hero_image_url ?? null;
              if (existingBrandingColumns.includes('promo_banner_image_url')) promoBannerImageUrl = s[0].promo_banner_image_url ?? null;
              if (existingBrandingColumns.includes('logo_url')) logoUrl = s[0].logo_url ?? null;
            }
          }
        }
      } catch {
        logger.warn('Error fetching cafe branding');
      }
      let banners: { id: number; image_url?: string; link_url?: string | null; priority?: number; active?: boolean }[] = [];
      try {
        banners = await PromoBanner.getActiveByCafeId(cafe.id);
      } catch {
        //
      }
      res.json({
        hero_image_url: heroImageUrl,
        promo_banner_image_url: promoBannerImageUrl,
        logo_url: logoUrl,
        banners: banners.length > 0 ? banners : undefined,
        cafe_name: cafe.name || null,
        address: cafe.address || null,
        phone: cafe.phone || null,
        email: cafe.email || null
      });
    } catch (error) {
      logger.error('Error fetching cafe branding:', error as Error);
      res.status(500).json({ error: 'Failed to fetch cafe branding' });
    }
  });

  app.put('/api/tax-settings', auth, adminAuth, requireOrderCafeScope, async (req: Request, res: Response) => {
    try {
      const cafeId = getOrderCafeId(req);
      const body = req.body as { tax_rate?: number | string; tax_name?: string; show_tax_in_menu?: boolean; include_tax?: boolean };
      const { tax_rate, tax_name, show_tax_in_menu, include_tax } = body;
      if (tax_rate === undefined || !tax_name) {
        return res.status(400).json({ error: 'Tax rate and tax name are required' });
      }
      const updatedSettings = await TaxSettings.update(
        {
          tax_rate: parseFloat(String(tax_rate)),
          tax_name: tax_name.trim(),
          show_tax_in_menu: show_tax_in_menu !== undefined ? show_tax_in_menu : true,
          include_tax: include_tax !== undefined ? include_tax : true
        },
        cafeId
      );
      res.json(updatedSettings);
    } catch (error) {
      logger.error('Error updating tax settings:', error as Error);
      res.status(500).json({ error: 'Failed to update tax settings' });
    }
  });

  app.get('/api/tax-settings/history', auth, adminAuth, requireOrderCafeScope, async (req: Request, res: Response) => {
    try {
      const cafeId = getOrderCafeId(req);
      const history = await TaxSettings.getHistory(cafeId);
      res.json(history);
    } catch (error) {
      logger.error('Error fetching tax history:', error as Error);
      res.status(500).json({ error: 'Failed to fetch tax history' });
    }
  });

  app.post('/api/calculate-tax', auth, async (req: Request, res: Response) => {
    try {
      const body = req.body as { subtotal?: number | string };
      const { subtotal } = body;
      if (subtotal === undefined) {
        return res.status(400).json({ error: 'Subtotal is required' });
      }
      const cafeId = getOrderCafeId(req);
      const taxCalculation = await TaxSettings.calculateTax(parseFloat(String(subtotal)), cafeId);
      res.json(taxCalculation);
    } catch (error) {
      logger.error('Error calculating tax:', error as Error);
      res.status(500).json({ error: 'Failed to calculate tax' });
    }
  });

  app.get('/api/currency-settings', async (req: Request, res: Response) => {
    try {
      let cafeId: number | null = null;
      const token = req.header('Authorization')?.replace('Bearer ', '');
      if (token) {
        try {
          const jwt = await import('jsonwebtoken');
          const decoded = jwt.verify(token, JWT_SECRET, { clockTolerance: 600 }) as { userId: number };
          const user = await User.findById(decoded.userId);
          if (user?.cafe_id) cafeId = user.cafe_id;
        } catch {
          //
        }
      }
      if (cafeId == null && req.query.cafeSlug) {
        const cafe = await Cafe.getBySlug(req.query.cafeSlug as string);
        if (cafe) cafeId = cafe.id;
      }
      const currencySettings = await CurrencySettings.getCurrent(cafeId);
      res.json(currencySettings);
    } catch (error) {
      logger.error('Error fetching currency settings:', error as Error);
      res.status(500).json({ error: 'Failed to fetch currency settings' });
    }
  });

  app.put('/api/currency-settings', auth, requireOrderCafeScope, async (req: Request, res: Response) => {
    try {
      const cafeId = getOrderCafeId(req);
      const body = req.body as { currency_code?: string; currency_symbol?: string; currency_name?: string };
      const { currency_code, currency_symbol, currency_name } = body;
      if (!currency_code || !currency_symbol || !currency_name) {
        return res.status(400).json({ error: 'Currency code, symbol, and name are required' });
      }
      const updatedSettings = await CurrencySettings.update(
        {
          currency_code: currency_code.trim(),
          currency_symbol: currency_symbol.trim(),
          currency_name: currency_name.trim()
        },
        cafeId
      );
      res.json(updatedSettings);
    } catch (error) {
      logger.error('Error updating currency settings:', error as Error);
      res.status(500).json({ error: 'Failed to update currency settings' });
    }
  });

  app.get('/api/currency-settings/history', auth, requireOrderCafeScope, async (req: Request, res: Response) => {
    try {
      const cafeId = getOrderCafeId(req);
      const history = await CurrencySettings.getHistory(cafeId);
      res.json(history);
    } catch (error) {
      logger.error('Error fetching currency history:', error as Error);
      res.status(500).json({ error: 'Failed to fetch currency history' });
    }
  });

  app.get('/api/currency-settings/available', async (req: Request, res: Response) => {
    try {
      const currencies = await CurrencySettings.getAvailableCurrencies();
      res.json(currencies);
    } catch (error) {
      logger.error('Error fetching available currencies:', error as Error);
      res.status(500).json({ error: 'Failed to fetch available currencies' });
    }
  });

  app.get('/api/cafe-settings', async (req: Request, res: Response) => {
    try {
      let cafeId: number | null = null;
      let cafeSlug: string | null = null;
      const token = req.header('Authorization')?.replace('Bearer ', '');
      if (token) {
        try {
          const jwt = await import('jsonwebtoken');
          const decoded = jwt.verify(token, JWT_SECRET, { clockTolerance: 600 }) as {
            userId: number;
            impersonatedCafeId?: number;
            impersonatedCafeSlug?: string;
          };
          const user = await User.findById(decoded.userId);
          if (user) {
            if (decoded.impersonatedCafeId) {
              cafeId = decoded.impersonatedCafeId;
              cafeSlug = decoded.impersonatedCafeSlug || null;
            } else {
              const userWithCafe = await User.findByIdWithCafe(user.id);
              if (userWithCafe?.cafe_id) {
                cafeId = userWithCafe.cafe_id;
                cafeSlug = userWithCafe.cafe_slug || null;
              }
            }
          }
        } catch {
          //
        }
      }
      if (cafeId === null && !token) {
        const slug = (req.query.cafeSlug as string) || 'default';
        try {
          const cafe = await Cafe.getBySlug(slug);
          if (cafe) {
            cafeId = cafe.id;
            cafeSlug = cafe.slug || slug;
          }
        } catch {
          //
        }
      }
      let cafeSettings = await CafeSettings.getCurrent(cafeId);
      if (cafeId && cafeSettings.cafe_id && cafeSettings.cafe_id !== cafeId) {
        return res.status(500).json({
          error: 'Cafe settings data mismatch. Please contact support.',
          details: `Requested cafe ID: ${cafeId}, but settings belong to cafe ID: ${cafeSettings.cafe_id}`
        });
      }
      const nameFromSettings = (cafeSettings.cafe_name || '').trim();
      const useCafeTableName = !nameFromSettings || /^default\s*cafe$/i.test(nameFromSettings);
      if (cafeId && useCafeTableName) {
        try {
          const cafe = await Cafe.getById(cafeId);
          if (cafe?.name) {
            cafeSettings = { ...cafeSettings, cafe_name: cafe.name };
            if (cafe.slug) (cafeSettings as Record<string, unknown>).cafe_slug = cafe.slug;
          }
        } catch {
          //
        }
      }
      res.json(cafeSettings);
    } catch (error) {
      logger.error('Error fetching cafe settings:', error as Error);
      res.status(500).json({ error: 'Failed to fetch cafe settings' });
    }
  });

  app.put('/api/cafe-settings', auth, async (req: Request, res: Response) => {
    try {
      const body = req.body as Record<string, unknown>;
      const cafe_name = body.cafe_name as string | undefined;
      if (!cafe_name) {
        return res.status(400).json({ error: 'Cafe name is required' });
      }
      let cafeId = getMenuCafeId(req);
      if (!cafeId && cafe_name) {
        try {
          const cafes = await Cafe.getAll();
          const matching = cafes.find((c) => c.name.toLowerCase() === cafe_name.toLowerCase().trim());
          if (matching) cafeId = matching.id;
        } catch {
          //
        }
      }
      if (!cafeId) {
        return res.status(400).json({
          error: 'Unable to determine cafe. Please ensure you are logged in and belong to a cafe.'
        });
      }
      let currentSettings: { logo_url?: string | null; hero_image_url?: string | null; promo_banner_image_url?: string | null } | null = null;
      try {
        currentSettings = await CafeSettings.getCurrent(cafeId) as { logo_url?: string | null; hero_image_url?: string | null; promo_banner_image_url?: string | null } | null;
      } catch {
        //
      }
      const existingLogo = currentSettings?.logo_url;
      const existingHero = currentSettings?.hero_image_url;
      const existingPromo = currentSettings?.promo_banner_image_url;
      const trimmedName = cafe_name.trim();
      const updatedSettings = await CafeSettings.update({
        ...body,
        cafe_id: cafeId,
        cafe_name: trimmedName,
        logo_url: body.logo_url !== undefined && body.logo_url !== '' ? (body.logo_url as string) : (existingLogo || '/images/palm-cafe-logo.png'),
        hero_image_url: body.hero_image_url !== undefined ? (body.hero_image_url as string) : (existingHero ?? null),
        promo_banner_image_url: body.promo_banner_image_url !== undefined ? (body.promo_banner_image_url as string) : (existingPromo ?? null),
        changed_by: req.user!.username
      } as Parameters<typeof CafeSettings.update>[0]);
      const cafeIdNum = parseInt(String(cafeId), 10);
      if (!Number.isNaN(cafeIdNum)) {
        try {
          const [cafeUpdateResult] = await pool.execute(
            'UPDATE cafes SET name = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?',
            [trimmedName, cafeIdNum]
          ) as [{ affectedRows: number }, unknown];
          if (cafeUpdateResult.affectedRows > 0) {
            const [cafeRows] = await pool.execute('SELECT slug FROM cafes WHERE id = ?', [cafeIdNum]) as [RowDataPacket[], unknown];
            const cr = cafeRows as (RowDataPacket & { slug?: string })[];
            if (cr.length > 0 && cr[0].slug) {
              Cafe.invalidateSlugCache(cr[0].slug);
            }
          }
        } catch (cafeUpdateErr) {
          logger.error('[PUT /api/cafe-settings] Failed to sync cafe name:', (cafeUpdateErr as Error).message);
        }
      }
      res.json(updatedSettings);
    } catch (error) {
      logger.error('Error updating cafe settings:', error as Error);
      res.status(500).json({
        error: 'Failed to update cafe settings',
        details: (error as Error).message,
        stack: process.env.NODE_ENV === 'development' ? (error as Error).stack : undefined
      });
    }
  });

  app.get('/api/cafe-settings/history', auth, async (req: Request, res: Response) => {
    try {
      const history = await CafeSettings.getHistory();
      res.json(history);
    } catch (error) {
      logger.error('Error fetching cafe settings history:', error as Error);
      res.status(500).json({ error: 'Failed to fetch cafe settings history' });
    }
  });

  app.post('/api/cafe-settings/logo', auth, imageUpload.single('logo'), async (req: Request, res: Response) => {
    try {
      let cafeId: number | null = null;
      if (req.user?.role === 'superadmin' && (req.body?.cafeId != null || req.query?.cafeId != null)) {
        const raw = (req.body as { cafeId?: unknown }).cafeId ?? req.query.cafeId;
        cafeId = parseInt(String(raw), 10);
        if (Number.isNaN(cafeId)) {
          return res.status(400).json({ error: 'Invalid cafeId for logo upload' });
        }
      } else {
        cafeId = req.user?.cafe_id ?? null;
      }
      if (!req.file) {
        return res.status(400).json({ error: 'No logo file uploaded' });
      }
      if (!cafeId) {
        return res.status(400).json({ error: 'User must be associated with a cafe or provide cafeId (super admin)' });
      }
      if (!req.file.mimetype.startsWith('image/')) {
        return res.status(400).json({ error: 'Only image files are allowed' });
      }
      const fileExtension = path.extname(req.file.originalname);
      const fileName = `cafe-logo-${Date.now()}${fileExtension}`;
      const filePath = path.join(publicImagesDir, fileName);
      const uploadDir = path.dirname(filePath);
      if (!fs.existsSync(uploadDir)) {
        fs.mkdirSync(uploadDir, { recursive: true });
      }
      fs.writeFileSync(filePath, req.file.buffer as Buffer);
      const logoUrl = `/images/${fileName}`;
      await CafeSettings.updateLogo(logoUrl, cafeId);
      res.json({ success: true, logo_url: logoUrl, message: 'Logo uploaded successfully' });
    } catch (error) {
      logger.error('[UPLOAD LOGO] Error:', error as Error);
      res.status(500).json({ error: 'Failed to upload logo', details: (error as Error).message });
    }
  });

  app.post('/api/cafe-settings/hero-image', auth, imageUpload.single('hero_image'), async (req: Request, res: Response) => {
    try {
      if (!req.file) {
        return res.status(400).json({ error: 'No hero image file uploaded' });
      }
      const cafeId = req.user?.cafe_id;
      if (!cafeId) {
        return res.status(400).json({ error: 'User must be associated with a cafe' });
      }
      if (!req.file.mimetype.startsWith('image/')) {
        return res.status(400).json({ error: 'Only image files are allowed' });
      }
      const maxSize = 5 * 1024 * 1024;
      if (req.file.size > maxSize) {
        return res.status(400).json({ error: 'Image size must be less than 5MB' });
      }
      const fileExtension = path.extname(req.file.originalname);
      const fileName = `cafe-hero-${Date.now()}${fileExtension}`;
      const filePath = path.join(publicImagesDir, fileName);
      const uploadDir = path.dirname(filePath);
      if (!fs.existsSync(uploadDir)) {
        fs.mkdirSync(uploadDir, { recursive: true });
      }
      fs.writeFileSync(filePath, req.file.buffer as Buffer);
      const heroImageUrl = `/images/${fileName}`;
      await CafeSettings.updateHeroImage(heroImageUrl, cafeId);
      res.json({ success: true, hero_image_url: heroImageUrl, message: 'Hero image uploaded successfully' });
    } catch (error) {
      logger.error('[UPLOAD HERO] Error:', error as Error);
      res.status(500).json({ error: 'Failed to upload hero image', details: (error as Error).message });
    }
  });

  app.post('/api/cafe-settings/promo-banner-image', auth, imageUpload.single('promo_banner_image'), async (req: Request, res: Response) => {
    try {
      if (!req.file) {
        return res.status(400).json({ error: 'No promo banner image file uploaded' });
      }
      const cafeId = req.user?.cafe_id;
      if (!cafeId) {
        return res.status(400).json({ error: 'User must be associated with a cafe' });
      }
      if (!req.file.mimetype.startsWith('image/')) {
        return res.status(400).json({ error: 'Only image files are allowed' });
      }
      const maxSize = 5 * 1024 * 1024;
      if (req.file.size > maxSize) {
        return res.status(400).json({ error: 'Image size must be less than 5MB' });
      }
      const fileExtension = path.extname(req.file.originalname);
      const fileName = `cafe-promo-banner-${Date.now()}${fileExtension}`;
      const filePath = path.join(publicImagesDir, fileName);
      const uploadDir = path.dirname(filePath);
      if (!fs.existsSync(uploadDir)) {
        fs.mkdirSync(uploadDir, { recursive: true });
      }
      fs.writeFileSync(filePath, req.file.buffer as Buffer);
      const promoBannerImageUrl = `/images/${fileName}`;
      await CafeSettings.updatePromoBannerImage(promoBannerImageUrl, cafeId);
      res.json({ success: true, promo_banner_image_url: promoBannerImageUrl, message: 'Promo banner image uploaded successfully' });
    } catch (error) {
      logger.error('[UPLOAD PROMO] Error:', error as Error);
      res.status(500).json({ error: 'Failed to upload promo banner image', details: (error as Error).message });
    }
  });

  app.delete('/api/cafe-settings/hero-image', auth, async (req: Request, res: Response) => {
    try {
      const cafeId = req.user?.cafe_id;
      if (!cafeId) {
        return res.status(400).json({ error: 'User must be associated with a cafe' });
      }
      await CafeSettings.updateHeroImage(null as unknown as string, cafeId);
      res.json({ success: true, message: 'Hero image removed successfully' });
    } catch (error) {
      logger.error('Error removing hero image:', error as Error);
      res.status(500).json({ error: 'Failed to remove hero image' });
    }
  });

  app.delete('/api/cafe-settings/promo-banner-image', auth, async (req: Request, res: Response) => {
    try {
      const cafeId = req.user?.cafe_id;
      if (!cafeId) {
        return res.status(400).json({ error: 'User must be associated with a cafe' });
      }
      await CafeSettings.updatePromoBannerImage(null as unknown as string, cafeId);
      res.json({ success: true, message: 'Promo banner image removed successfully' });
    } catch (error) {
      logger.error('Error removing promo banner image:', error as Error);
      res.status(500).json({ error: 'Failed to remove promo banner image' });
    }
  });

  app.get('/api/promo-banners', auth, adminAuth, requireOrderCafeScope, async (req: Request, res: Response) => {
    try {
      const cafeId = getOrderCafeId(req);
      if (!cafeId) {
        return res.status(400).json({ error: 'User must be associated with a cafe' });
      }
      const banners = await PromoBanner.getByCafeId(cafeId);
      res.json(banners);
    } catch (error) {
      logger.error('Error fetching promo banners:', error as Error);
      res.status(500).json({ error: 'Failed to fetch promo banners' });
    }
  });

  app.post('/api/promo-banners', auth, adminAuth, requireOrderCafeScope, imageUpload.single('image'), async (req: Request, res: Response) => {
    try {
      const cafeId = getOrderCafeId(req);
      if (!cafeId) {
        return res.status(400).json({ error: 'User must be associated with a cafe' });
      }
      if (!req.file) {
        return res.status(400).json({ error: 'No image file uploaded' });
      }
      if (!req.file.mimetype.startsWith('image/')) {
        return res.status(400).json({ error: 'Only image files are allowed' });
      }
      const maxSize = 5 * 1024 * 1024;
      if (req.file.size > maxSize) {
        return res.status(400).json({ error: 'Image size must be less than 5MB' });
      }
      const fileExtension = path.extname(req.file.originalname) || '.jpg';
      const fileName = `promo-banner-${Date.now()}-${cafeId}${fileExtension}`;
      const filePath = path.join(publicImagesDir, fileName);
      const uploadDir = path.dirname(filePath);
      if (!fs.existsSync(uploadDir)) {
        fs.mkdirSync(uploadDir, { recursive: true });
      }
      fs.writeFileSync(filePath, req.file.buffer as Buffer);
      const imageUrl = `/images/${fileName}`;
      const linkUrl = req.body.link_url ? String(req.body.link_url).trim() || null : null;
      const priority = req.body.priority != null && !Number.isNaN(Number(req.body.priority)) ? Number(req.body.priority) : 0;
      const active = req.body.active !== 'false' && req.body.active !== false;
      const banner = await PromoBanner.create({ cafe_id: cafeId, image_url: imageUrl, link_url: linkUrl, priority, active });
      res.status(201).json(banner);
    } catch (error) {
      logger.error('Error creating promo banner:', error as Error);
      res.status(500).json({ error: 'Failed to create promo banner', details: (error as Error).message });
    }
  });

  app.put('/api/promo-banners/:id', auth, adminAuth, requireOrderCafeScope, async (req: Request, res: Response) => {
    try {
      const cafeId = getOrderCafeId(req);
      if (!cafeId) {
        return res.status(400).json({ error: 'User must be associated with a cafe' });
      }
      const id = parseInt(req.params.id, 10);
      if (!Number.isInteger(id) || id < 1) {
        return res.status(400).json({ error: 'Invalid banner id' });
      }
      const body = req.body as { link_url?: string; priority?: number; active?: boolean };
      const { link_url, priority, active } = body;
      const data: Record<string, unknown> = {};
      if (link_url !== undefined) data.link_url = link_url;
      if (priority !== undefined) data.priority = Number(priority);
      if (active !== undefined) data.active = active;
      const updated = await PromoBanner.update(id, cafeId, data);
      if (!updated) {
        return res.status(404).json({ error: 'Banner not found' });
      }
      res.json(updated);
    } catch (error) {
      logger.error('Error updating promo banner:', error as Error);
      res.status(500).json({ error: 'Failed to update promo banner', details: (error as Error).message });
    }
  });

  app.patch('/api/promo-banners/:id/image', auth, adminAuth, requireOrderCafeScope, imageUpload.single('image'), async (req: Request, res: Response) => {
    try {
      const cafeId = getOrderCafeId(req);
      if (!cafeId) {
        return res.status(400).json({ error: 'User must be associated with a cafe' });
      }
      const id = parseInt(req.params.id, 10);
      if (!Number.isInteger(id) || id < 1) {
        return res.status(400).json({ error: 'Invalid banner id' });
      }
      if (!req.file) {
        return res.status(400).json({ error: 'No image file uploaded' });
      }
      if (!req.file.mimetype.startsWith('image/')) {
        return res.status(400).json({ error: 'Only image files are allowed' });
      }
      const maxSize = 5 * 1024 * 1024;
      if (req.file.size > maxSize) {
        return res.status(400).json({ error: 'Image size must be less than 5MB' });
      }
      const fileExtension = path.extname(req.file.originalname) || '.jpg';
      const fileName = `promo-banner-${Date.now()}-${cafeId}-${id}${fileExtension}`;
      const filePath = path.join(publicImagesDir, fileName);
      const uploadDir = path.dirname(filePath);
      if (!fs.existsSync(uploadDir)) {
        fs.mkdirSync(uploadDir, { recursive: true });
      }
      fs.writeFileSync(filePath, req.file.buffer as Buffer);
      const imageUrl = `/images/${fileName}`;
      const updated = await PromoBanner.update(id, cafeId, { image_url: imageUrl });
      if (!updated) {
        return res.status(404).json({ error: 'Banner not found' });
      }
      res.json(updated);
    } catch (error) {
      logger.error('Error replacing promo banner image:', error as Error);
      res.status(500).json({ error: 'Failed to replace banner image', details: (error as Error).message });
    }
  });

  app.delete('/api/promo-banners/:id', auth, adminAuth, requireOrderCafeScope, async (req: Request, res: Response) => {
    try {
      const cafeId = getOrderCafeId(req);
      if (!cafeId) {
        return res.status(400).json({ error: 'User must be associated with a cafe' });
      }
      const id = parseInt(req.params.id, 10);
      if (!Number.isInteger(id) || id < 1) {
        return res.status(400).json({ error: 'Invalid banner id' });
      }
      const deleted = await PromoBanner.delete(id, cafeId);
      if (!deleted) {
        return res.status(404).json({ error: 'Banner not found' });
      }
      res.json({ success: true, message: 'Banner deleted' });
    } catch (error) {
      logger.error('Error deleting promo banner:', error as Error);
      res.status(500).json({ error: 'Failed to delete promo banner', details: (error as Error).message });
    }
  });

  app.delete('/api/cafe-settings/logo', auth, async (req: Request, res: Response) => {
    try {
      const cafeId = req.user?.cafe_id;
      if (!cafeId) {
        return res.status(400).json({ error: 'User must be associated with a cafe' });
      }
      await CafeSettings.updateLogo(null as unknown as string, cafeId);
      res.json({ success: true, message: 'Logo removed successfully' });
    } catch (error) {
      logger.error('Error removing logo:', error as Error);
      res.status(500).json({ error: 'Failed to remove logo' });
    }
  });

  app.post('/api/menu/upload-image', auth, imageUpload.single('image'), async (req: Request, res: Response) => {
    try {
      if (!req.file) {
        return res.status(400).json({ error: 'No image file uploaded' });
      }
      if (!req.file.mimetype.startsWith('image/')) {
        return res.status(400).json({ error: 'Only image files are allowed' });
      }
      const maxSize = 5 * 1024 * 1024;
      if (req.file.size > maxSize) {
        return res.status(400).json({ error: 'Image size must be less than 5MB' });
      }
      const fileExtension = path.extname(req.file.originalname);
      const fileName = `menu-item-${Date.now()}${fileExtension}`;
      const filePath = path.join(publicImagesDir, fileName);
      const uploadDir = path.dirname(filePath);
      if (!fs.existsSync(uploadDir)) {
        fs.mkdirSync(uploadDir, { recursive: true });
      }
      fs.writeFileSync(filePath, req.file.buffer as Buffer);
      const imageUrl = `/images/${fileName}`;
      res.json({ success: true, image_url: imageUrl, message: 'Image uploaded successfully' });
    } catch (error) {
      logger.error('Error uploading menu item image:', error as Error);
      res.status(500).json({ error: 'Failed to upload image' });
    }
  });

  app.post('/api/menu/:id/image', auth, requireCafeMembership, imageUpload.single('image'), async (req: Request, res: Response) => {
    try {
      const id = req.params.id as string;
      const menuItemId = parseInt(id, 10);
      if (!req.file) {
        return res.status(400).json({ error: 'No image file uploaded' });
      }
      if (!req.file.mimetype.startsWith('image/')) {
        return res.status(400).json({ error: 'Only image files are allowed' });
      }
      const maxSize = 5 * 1024 * 1024;
      if (req.file.size > maxSize) {
        return res.status(400).json({ error: 'Image size must be less than 5MB' });
      }
      const menuItem = await MenuItem.getById(menuItemId);
      if (!menuItem) {
        return res.status(404).json({ error: 'Menu item not found' });
      }
      if (menuItem.cafe_id && req.user?.cafe_id && menuItem.cafe_id !== req.user.cafe_id) {
        if (req.user.role !== 'superadmin') {
          return res.status(403).json({ error: 'Access denied. You do not have permission to modify this menu item.' });
        }
      }
      if (menuItem.image_url && menuItem.image_url.startsWith('/images/')) {
        const oldImagePath = path.join(publicImagesDir, path.basename(menuItem.image_url));
        try {
          if (fs.existsSync(oldImagePath)) {
            fs.unlinkSync(oldImagePath);
          }
        } catch (err) {
          logger.error('Error deleting old image:', err as Error);
        }
      }
      const fileExtension = path.extname(req.file.originalname);
      const fileName = `menu-item-${id}-${Date.now()}${fileExtension}`;
      const filePath = path.join(publicImagesDir, fileName);
      const uploadDir = path.dirname(filePath);
      if (!fs.existsSync(uploadDir)) {
        fs.mkdirSync(uploadDir, { recursive: true });
      }
      fs.writeFileSync(filePath, req.file.buffer as Buffer);
      const imageUrl = `/images/${fileName}`;
      const updatePayload = {
        category_id: menuItem.category_id,
        name: menuItem.name,
        description: menuItem.description || '',
        price: menuItem.price,
        sort_order: menuItem.sort_order,
        is_available: menuItem.is_available,
        image_url: imageUrl,
        featured_priority: menuItem.featured_priority
      };
      const updatedItem = await MenuItem.update(menuItemId, updatePayload, menuItem.cafe_id ?? null);
      res.json({ success: true, image_url: imageUrl, menu_item: updatedItem, message: 'Image uploaded successfully' });
    } catch (error) {
      logger.error('Error uploading menu item image:', error as Error);
      res.status(500).json({ error: 'Failed to upload image' });
    }
  });

  app.delete('/api/menu/:id/image', auth, requireCafeMembership, async (req: Request, res: Response) => {
    try {
      const id = req.params.id as string;
      const menuItemId = parseInt(id, 10);
      const menuItem = await MenuItem.getById(menuItemId);
      if (!menuItem) {
        return res.status(404).json({ error: 'Menu item not found' });
      }
      if (menuItem.cafe_id && req.user?.cafe_id && menuItem.cafe_id !== req.user.cafe_id) {
        if (req.user.role !== 'superadmin') {
          return res.status(403).json({ error: 'Access denied. You do not have permission to modify this menu item.' });
        }
      }
      if (menuItem.image_url && menuItem.image_url.startsWith('/images/')) {
        const imagePath = path.join(publicImagesDir, path.basename(menuItem.image_url));
        try {
          if (fs.existsSync(imagePath)) {
            fs.unlinkSync(imagePath);
          }
        } catch (err) {
          logger.error('Error deleting image file:', err as Error);
        }
      }
      const updatedItem = await MenuItem.update(
        menuItemId,
        {
          category_id: menuItem.category_id,
          name: menuItem.name,
          description: menuItem.description || '',
          price: menuItem.price,
          sort_order: menuItem.sort_order,
          is_available: menuItem.is_available,
          image_url: null,
          featured_priority: menuItem.featured_priority
        },
        menuItem.cafe_id ?? null
      );
      res.json({ success: true, menu_item: updatedItem, message: 'Image removed successfully' });
    } catch (error) {
      logger.error('Error removing menu item image:', error as Error);
      res.status(500).json({ error: 'Failed to remove image' });
    }
  });
}
