apiVersion: v1
kind: Secret
metadata:
  name: palm-cafe-api-secrets
  namespace: palm-cafe
type: Opaque
stringData:
  DB_HOST: 'your-managed-db-host'
  DB_USER: 'your-db-user'
  DB_PASSWORD: 'your-db-password'
  DB_NAME: 'your-db-name'
  JWT_SECRET: 'replace-with-min-32-char-secret'
  REDIS_URL: 'redis://your-redis-host:6379'
  FRONTEND_URL: 'https://app.example.com'
  ADMIN_URL: 'https://app.example.com'
